<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'ID' => 1,
                'Nama' => 'Admin',
                'JK' => NULL,
                'TmpLahir' => NULL,
                'TglLahir' => NULL,
                'Agama' => NULL,
                'Pendidikan' => NULL,
                'Alamat' => NULL,
                'Alamat_dom' => '',
                'Kota' => NULL,
                'KodePos' => NULL,
                'Telpon' => NULL,
                'KTP' => NULL,
                'Status' => NULL,
                'JA' => 0,
                'TglMasuk' => NULL,
                'TglLulus' => NULL,
                'TglUpdate' => '2025-01-03 02:22:38',
                'Aktif' => 0,
                'TglKeluar' => NULL,
                'Jabatan' => NULL,
                'Divisi' => NULL,
                'Dept' => NULL,
                'Cabang' => NULL,
                'Golongan' => NULL,
                'jeniskar' => NULL,
                'statuskar' => '',
                'no_bpjs_tk' => NULL,
                'no_bpjs_kes' => NULL,
                'tgl_keper_bpjs' => NULL,
                'statBpjs' => NULL,
                'Atasan' => NULL,
                'JamKerja' => NULL,
                'total_telat' => NULL,
                'NoSuratKerja' => NULL,
                'NoSuratKerja2' => NULL,
                'MasaBerlaku' => NULL,
                'MasaBerlaku2' => NULL,
                'TjMakan' => NULL,
                'stat_makan' => NULL,
                'NilaiTjMakan' => 0,
                'TjBBM' => NULL,
                'NilaiTjBBM' => 0,
                'stat_BBM' => NULL,
                'TjAsuransi' => NULL,
                'TjAssEff' => NULL,
                'TjAssPolis' => NULL,
                'TjPengobatan' => 0,
                'TjKerajinan' => 0,
                'TjLembur' => 0,
                'SaldoTjPengobatan' => 0,
                'TjUmObMinggu' => 0,
                'IDMesin' => 0,
                'StatusNoPrick' => 0,
                'Pajak' => 0,
                'Npwp' => NULL,
                'hak_cuti' => NULL,
                'jml_cuti' => 0,
                'jml_off' => 0,
                'nokk' => NULL,
                'email_karyawan' => NULL,
                'email_atasan' => NULL,
                'uname' => 'admin',
                'pwd' => 'admin-hrd',
                'lvl' => 1,
                'abs' => 0,
                'created_at' => '2024-10-28 06:10:22',
                'updated_at' => '2025-01-02 21:35:57',
            ],
            [
                'ID' => 2,
                'Nama' => 'admin-tgr',
                'JK' => NULL,
                'TmpLahir' => NULL,
                'TglLahir' => NULL,
                'Agama' => NULL,
                'Pendidikan' => NULL,
                'Alamat' => NULL,
                'Alamat_dom' => '',
                'Kota' => NULL,
                'KodePos' => NULL,
                'Telpon' => NULL,
                'KTP' => NULL,
                'Status' => NULL,
                'JA' => 0,
                'TglMasuk' => NULL,
                'TglLulus' => NULL,
                'TglUpdate' => '2025-01-03 02:22:38',
                'Aktif' => 0,
                'TglKeluar' => NULL,
                'Jabatan' => NULL,
                'Divisi' => NULL,
                'Dept' => NULL,
                'Cabang' => NULL,
                'Golongan' => NULL,
                'jeniskar' => NULL,
                'statuskar' => '',
                'no_bpjs_tk' => NULL,
                'no_bpjs_kes' => NULL,
                'tgl_keper_bpjs' => NULL,
                'statBpjs' => NULL,
                'Atasan' => NULL,
                'JamKerja' => NULL,
                'total_telat' => NULL,
                'NoSuratKerja' => NULL,
                'NoSuratKerja2' => NULL,
                'MasaBerlaku' => NULL,
                'MasaBerlaku2' => NULL,
                'TjMakan' => NULL,
                'stat_makan' => NULL,
                'NilaiTjMakan' => 0,
                'TjBBM' => NULL,
                'NilaiTjBBM' => 0,
                'stat_BBM' => NULL,
                'TjAsuransi' => NULL,
                'TjAssEff' => NULL,
                'TjAssPolis' => NULL,
                'TjPengobatan' => 0,
                'TjKerajinan' => 0,
                'TjLembur' => 0,
                'SaldoTjPengobatan' => 0,
                'TjUmObMinggu' => 0,
                'IDMesin' => 0,
                'StatusNoPrick' => 0,
                'Pajak' => 0,
                'Npwp' => NULL,
                'hak_cuti' => NULL,
                'jml_cuti' => 0,
                'jml_off' => 0,
                'nokk' => NULL,
                'email_karyawan' => NULL,
                'email_atasan' => NULL,
                'uname' => 'admin-tgr',
                'pwd' => 'tgr321',
                'lvl' => 1,
                'abs' => 0,
                'created_at' => '2024-10-28 06:10:22',
                'updated_at' => '2025-01-02 21:35:57',
            ],
            [
                'ID' => 3,
                'Nama' => 'admin-ga',
                'JK' => NULL,
                'TmpLahir' => NULL,
                'TglLahir' => NULL,
                'Agama' => NULL,
                'Pendidikan' => NULL,
                'Alamat' => NULL,
                'Alamat_dom' => '',
                'Kota' => NULL,
                'KodePos' => NULL,
                'Telpon' => NULL,
                'KTP' => NULL,
                'Status' => NULL,
                'JA' => 0,
                'TglMasuk' => NULL,
                'TglLulus' => NULL,
                'TglUpdate' => '2025-01-17 14:22:38',
                'Aktif' => 0,
                'TglKeluar' => NULL,
                'Jabatan' => NULL,
                'Divisi' => NULL,
                'Dept' => NULL,
                'Cabang' => NULL,
                'Golongan' => NULL,
                'jeniskar' => NULL,
                'statuskar' => '',
                'no_bpjs_tk' => NULL,
                'no_bpjs_kes' => NULL,
                'tgl_keper_bpjs' => NULL,
                'statBpjs' => NULL,
                'Atasan' => NULL,
                'JamKerja' => NULL,
                'total_telat' => NULL,
                'NoSuratKerja' => NULL,
                'NoSuratKerja2' => NULL,
                'MasaBerlaku' => NULL,
                'MasaBerlaku2' => NULL,
                'TjMakan' => NULL,
                'stat_makan' => NULL,
                'NilaiTjMakan' => 0,
                'TjBBM' => NULL,
                'NilaiTjBBM' => 0,
                'stat_BBM' => NULL,
                'TjAsuransi' => NULL,
                'TjAssEff' => NULL,
                'TjAssPolis' => NULL,
                'TjPengobatan' => 0,
                'TjKerajinan' => 0,
                'TjLembur' => 0,
                'SaldoTjPengobatan' => 0,
                'TjUmObMinggu' => 0,
                'IDMesin' => 0,
                'StatusNoPrick' => 0,
                'Pajak' => 0,
                'Npwp' => NULL,
                'hak_cuti' => NULL,
                'jml_cuti' => 0,
                'jml_off' => 0,
                'nokk' => NULL,
                'email_karyawan' => NULL,
                'email_atasan' => NULL,
                'uname' => 'admin-ga',
                'pwd' => 'admin-ga123',
                'lvl' => 1,
                'abs' => 0,
                'created_at' => '2025-01-17 14:22:22',
                'updated_at' => '2025-01-17 14:22:57',
            ],
        ]);
    }
}
